package codegen

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"

	"github.com/apptivitypl/rill/internal/schema"
)

const RillImport = "github.com/apptivitypl/rill"

type File struct {
	Package    string
	Imports    []string
	SourceFile string
	SourceLine int
	Source     string
	Schema     *schema.Schema
}

func Render(file File) ([]byte, error) {
	hoisted, parts := SplitImports(file.Source)

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by rill. DO NOT EDIT.\n\npackage %s\n\n", file.Package)
	writeImports(&b, append(quoted(file.Imports), hoisted...))

	written := false
	for _, part := range parts {
		if strings.TrimSpace(part.Text) == "" {
			continue
		}
		fmt.Fprintf(&b, "//line %s:%d\n", file.SourceFile, file.SourceLine+part.Line-1)
		b.WriteString(part.Text)
		if !strings.HasSuffix(part.Text, "\n") {
			b.WriteString("\n")
		}
		written = true
	}
	if written {
		b.WriteString("\n//line generated.go:1\n")
	}

	if file.Schema != nil {
		for _, name := range enumNames(file.Schema) {
			writeEnum(&b, file.Schema.Enums[name])
		}
		for _, name := range file.Schema.Order {
			value, _ := file.Schema.Get(name)
			writeAccessor(&b, value, file.Schema)
		}
	}

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return []byte(b.String()), fmt.Errorf("generated code does not parse: %w", err)
	}
	return formatted, nil
}

func quoted(paths []string) []string {
	specs := make([]string, 0, len(paths))
	for _, path := range paths {
		specs = append(specs, strconv.Quote(path))
	}
	return specs
}

func writeImports(b *strings.Builder, imports []string) {
	all := append([]string{strconv.Quote(RillImport)}, imports...)
	sort.Strings(all)
	all = dedupe(all)

	b.WriteString("import (\n")
	for _, spec := range all {
		fmt.Fprintf(b, "\t%s\n", spec)
	}
	b.WriteString(")\n\nvar _ = rill.Nil\n\n")
}

func dedupe(values []string) []string {
	out := values[:0]
	var previous string
	for i, value := range values {
		if i > 0 && value == previous {
			continue
		}
		previous = value
		out = append(out, value)
	}
	return out
}

const caseMethod = "rillCase"

func enumNames(model *schema.Schema) []string {
	names := make([]string, 0, len(model.Enums))
	for name, enum := range model.Enums {
		if len(enum.Members) > 0 {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	return names
}

func writeEnum(b *strings.Builder, enum schema.Enum) {
	fmt.Fprintf(b, "func (v %s) %s() string {\n\tswitch v {\n", enum.Name, caseMethod)
	for _, member := range enum.Members {
		fmt.Fprintf(b, "\tcase %s:\n\t\treturn %q\n", member, member)
	}
	b.WriteString("\t}\n\treturn \"\"\n}\n\n")
}

func writeAccessor(b *strings.Builder, value schema.Struct, all *schema.Schema) {
	fmt.Fprintf(b, "func (v %s) Get(path []string) (rill.Value, bool) {\n", value.Name)
	b.WriteString("\tif len(path) == 0 {\n\t\treturn rill.Nil(), false\n\t}\n")
	b.WriteString("\tswitch path[0] {\n")
	for _, field := range value.Fields {
		if field.Deferred {
			continue
		}
		fmt.Fprintf(b, "\tcase %q:\n", field.Name)
		writeField(b, field, all)
	}
	b.WriteString("\t}\n\treturn rill.Nil(), false\n}\n\n")
	writeNames(b, value)
	for _, field := range value.Fields {
		if field.Deferred {
			writeDeferred(b, field, all)
		}
	}
}

const DeferredPrefix = "deferred"

func writeDeferred(b *strings.Builder, field schema.Field, all *schema.Schema) {
	name := DeferredPrefix + field.Name
	fmt.Fprintf(b, "type %s struct {\n\tvalue %s\n}\n\n", name, typeName(field.Type, all))
	fmt.Fprintf(b, "func (d %s) Get(path []string) (rill.Value, bool) {\n", name)
	b.WriteString("\tif len(path) == 0 {\n")
	fmt.Fprintf(b, "\t\treturn %s, true\n", deferredValue(field.Type, "d.value", all))
	b.WriteString("\t}\n")
	if field.Type.Kind == schema.KindStruct && all.Has(field.Type.Name) {
		b.WriteString("\treturn d.value.Get(path)\n}\n\n")
		return
	}
	b.WriteString("\treturn rill.Nil(), false\n}\n\n")
}

func deferredValue(fieldType schema.Type, access string, all *schema.Schema) string {
	switch fieldType.Kind {
	case schema.KindSlice:
		return fmt.Sprintf("rill.Seq(%s)", sequence(*fieldType.Elem, access, all))
	case schema.KindStruct:
		if all.Has(fieldType.Name) {
			return fmt.Sprintf("rill.Object(%s)", access)
		}
		return "rill.Nil()"
	default:
		return scalar(fieldType, access)
	}
}

func typeName(fieldType schema.Type, all *schema.Schema) string {
	switch fieldType.Kind {
	case schema.KindSlice:
		return "[]" + typeName(*fieldType.Elem, all)
	case schema.KindOptional:
		return "*" + typeName(*fieldType.Elem, all)
	case schema.KindString:
		return primitive(fieldType, "string")
	case schema.KindInt:
		return primitive(fieldType, "int")
	case schema.KindFloat:
		return primitive(fieldType, "float64")
	case schema.KindBool:
		return primitive(fieldType, "bool")
	default:
		return fieldType.Name
	}
}

func primitive(fieldType schema.Type, fallback string) string {
	if fieldType.Name != "" {
		return fieldType.Name
	}
	return fallback
}

func writeNames(b *strings.Builder, value schema.Struct) {
	fmt.Fprintf(b, "func (v %s) Names() []string {\n", value.Name)
	b.WriteString("\treturn []string{")
	for i, field := range value.Fields {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%q", field.Name)
	}
	b.WriteString("}\n}\n\n")
}

func writeField(b *strings.Builder, field schema.Field, all *schema.Schema) {
	access := "v." + field.Name
	if field.Computed {
		access += "()"
	}
	switch field.Type.Kind {
	case schema.KindStruct:
		if all.Has(field.Type.Name) {
			b.WriteString("\t\tif len(path) > 1 {\n")
			fmt.Fprintf(b, "\t\t\treturn %s.Get(path[1:])\n", access)
			b.WriteString("\t\t}\n")
			fmt.Fprintf(b, "\t\treturn rill.Object(%s), true\n", access)
			return
		}
		b.WriteString("\t\treturn rill.Nil(), false\n")
	case schema.KindOptional:
		writeOptional(b, field, access, all)
	case schema.KindSlice:
		b.WriteString("\t\tif len(path) != 1 {\n\t\t\treturn rill.Nil(), false\n\t\t}\n")
		fmt.Fprintf(b, "\t\treturn rill.Seq(%s), true\n", sequence(*field.Type.Elem, access, all))
	default:
		b.WriteString("\t\tif len(path) != 1 {\n\t\t\treturn rill.Nil(), false\n\t\t}\n")
		fmt.Fprintf(b, "\t\treturn %s, true\n", scalar(field.Type, access))
	}
}

func writeOptional(b *strings.Builder, field schema.Field, access string, all *schema.Schema) {
	elem := *field.Type.Elem
	fmt.Fprintf(b, "\t\tif %s == nil {\n\t\t\treturn rill.Nil(), len(path) == 1\n\t\t}\n", access)
	if elem.Kind == schema.KindStruct && all.Has(elem.Name) {
		b.WriteString("\t\tif len(path) > 1 {\n")
		fmt.Fprintf(b, "\t\t\treturn (*%s).Get(path[1:])\n", access)
		b.WriteString("\t\t}\n")
		fmt.Fprintf(b, "\t\treturn rill.Object(*%s), true\n", access)
		return
	}
	b.WriteString("\t\tif len(path) != 1 {\n\t\t\treturn rill.Nil(), false\n\t\t}\n")
	fmt.Fprintf(b, "\t\treturn %s, true\n", scalar(elem, "(*"+access+")"))
}

func scalar(fieldType schema.Type, access string) string {
	switch fieldType.Kind {
	case schema.KindEnum:
		return fmt.Sprintf("rill.String(%s.%s())", access, caseMethod)
	case schema.KindString:
		return fmt.Sprintf("rill.String(string(%s))", access)
	case schema.KindInt:
		return fmt.Sprintf("rill.Int(int64(%s))", access)
	case schema.KindFloat:
		return fmt.Sprintf("rill.Float(float64(%s))", access)
	case schema.KindBool:
		return fmt.Sprintf("rill.Bool(bool(%s))", access)
	default:
		return "rill.Nil()"
	}
}

func sequence(elem schema.Type, access string, all *schema.Schema) string {
	switch {
	case elem.Kind == schema.KindEnum:
		return fmt.Sprintf("rill.Cases[%s](%s)", elem.Name, access)
	case elem.Kind == schema.KindStruct && all.Has(elem.Name):
		return fmt.Sprintf("rill.Objects[%s](%s)", elem.Name, access)
	case elem.Kind == schema.KindString:
		return fmt.Sprintf("rill.Strings(%s)", access)
	case elem.Kind == schema.KindInt:
		return fmt.Sprintf("rill.Ints[%s](%s)", elem.Name, access)
	case elem.Kind == schema.KindFloat:
		return fmt.Sprintf("rill.Floats[%s](%s)", elem.Name, access)
	case elem.Kind == schema.KindBool:
		return fmt.Sprintf("rill.Bools(%s)", access)
	default:
		return "rill.Strings(nil)"
	}
}

func PackageName(routeName string) string {
	var b strings.Builder
	for i := range len(routeName) {
		c := routeName[i]
		switch {
		case c >= 'a' && c <= 'z', c >= '0' && c <= '9':
			b.WriteByte(c)
		case c >= 'A' && c <= 'Z':
			b.WriteByte(c - 'A' + 'a')
		default:
			b.WriteByte('_')
		}
	}
	name := b.String()
	if name == "" || (name[0] >= '0' && name[0] <= '9') || reserved[name] {
		return "route_" + name
	}
	return name
}

var reserved = map[string]bool{
	"break": true, "case": true, "chan": true, "const": true, "continue": true,
	"default": true, "defer": true, "else": true, "fallthrough": true, "for": true,
	"func": true, "go": true, "goto": true, "if": true, "import": true,
	"interface": true, "map": true, "package": true, "range": true, "return": true,
	"select": true, "struct": true, "switch": true, "type": true, "var": true,
	"any": true, "bool": true, "byte": true, "error": true, "false": true,
	"float32": true, "float64": true, "int": true, "int8": true, "int16": true,
	"int32": true, "int64": true, "len": true, "new": true, "nil": true,
	"rune": true, "string": true, "true": true, "uint": true, "uint8": true,
	"uint16": true, "uint32": true, "uint64": true,
}
