package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/sonquer/rill/internal/schema"
)

const TypesFile = "props.generated.ts"

func TypeScript(model *schema.Schema) string {
	if model == nil {
		return ""
	}
	var b strings.Builder
	b.WriteString("// Code generated by rill. DO NOT EDIT.\n\n")
	for _, name := range allEnumNames(model) {
		writeUnion(&b, model.Enums[name])
	}
	for _, name := range model.Order {
		value, ok := model.Get(name)
		if !ok {
			continue
		}
		writeInterface(&b, value, model)
	}
	return b.String()
}

func allEnumNames(model *schema.Schema) []string {
	names := make([]string, 0, len(model.Enums))
	for name := range model.Enums {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func writeUnion(b *strings.Builder, enum schema.Enum) {
	if len(enum.Members) == 0 {
		fmt.Fprintf(b, "export type %s = string;\n\n", enum.Name)
		return
	}
	members := make([]string, 0, len(enum.Members))
	for _, member := range enum.Members {
		members = append(members, fmt.Sprintf("%q", member))
	}
	fmt.Fprintf(b, "export type %s = %s;\n\n", enum.Name, strings.Join(members, " | "))
}

func writeInterface(b *strings.Builder, value schema.Struct, model *schema.Schema) {
	fmt.Fprintf(b, "export interface %s {\n", value.Name)
	for _, field := range value.Fields {
		optional := ""
		if field.Type.Kind == schema.KindOptional {
			optional = "?"
		}
		fmt.Fprintf(b, "\t%s%s: %s;\n", field.Name, optional, typeScriptType(field.Type, model))
	}
	b.WriteString("}\n\n")
}

func typeScriptType(typ schema.Type, model *schema.Schema) string {
	switch typ.Kind {
	case schema.KindString:
		return "string"
	case schema.KindInt, schema.KindFloat:
		return "number"
	case schema.KindBool:
		return "boolean"
	case schema.KindEnum:
		return typ.Name
	case schema.KindSlice:
		return typeScriptType(*typ.Elem, model) + "[]"
	case schema.KindOptional:
		return typeScriptType(*typ.Elem, model) + " | null"
	case schema.KindStruct:
		if model.Has(typ.Name) {
			return typ.Name
		}
		return "unknown"
	default:
		return "unknown"
	}
}
